name: video_editing_app
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies:

  get_cli: ^1.8.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  get: 4.6.4
  flutter_svg: ^1.1.5
  dropdown_button2: ^1.8.9
  badges: ^2.0.3

  flutter: 
    sdk: flutter
  nb_utils: ^4.6.25
  html: ^0.15.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  otp_text_field: ^1.1.3
  jwt_decode: ^0.3.1
  logger: ^1.1.0
  async: ^2.9.0
  web_socket_channel: ^2.2.0
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.13
  image_picker: ^0.8.6+2
  country_picker: ^2.0.19
  cached_video_player: ^2.0.4
  video_thumbnail: ^0.5.3
  video_thumbnail_imageview: ^0.0.5
  path_provider:

dev_dependencies: 
  flutter_lints: ^2.0.0
  firebase_core_platform_interface:
  flutter_test: 
    sdk: flutter

flutter:

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    -
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf


  uses-material-design: true

